#!/bin/bash

# threshold values
CPU_THRESHOLD=70
MEMORY_THRESHOLD=75
DISK_THRESHOLD=90

# mail to send the alert
EMAIL="victorjoly40@gmail.com"


# Check CPU usage
check_cpu() {
  CPU_USAGE=$(mpstat 1 1 | awk '/Average/ {print 100 - $NF}')
  echo $CPU_USAGE
}

# Check RAM usage
check_memory() {
  MEMORY_USAGE=$(free -m | awk 'NR==2{printf "%.2f", $3*100/$2 }')
  echo $MEMORY_USAGE
}

# Check disk usage
check_disk() {
  DISK_USAGE=$(df -h --total | grep 'total' | awk '{print $5}' | tr -d '%')
  echo $DISK_USAGE
}

send_alert() {
  local resource=$1
  local usage=$2
  local threshold=$3

  SUBJECT="Alert: High usage of $resource"
  MESSAGE="The usage of $resource has reached $usage%, which exceeds $threshold%."

  echo $MESSAGE | mail -s "$SUBJECT" $EMAIL
}

VALUE=0
# Monitoring loop
while true; do
  CPU_USAGE=$(check_cpu)
  MEMORY_USAGE=$(check_memory)
  DISK_USAGE=$(check_disk)

  
  if [ $VALUE -ge 60 ]; then
    VALUE=0
  fi
  # debugging
  echo "$VALUE"

  # Display the values for debugging in Bashsys.log
  echo "CPU Usage: $CPU_USAGE%"
  echo "Memory Usage: $MEMORY_USAGE%"
  echo "Disk Usage: $DISK_USAGE%"

  # if statements to check if the value is superior to the threshold
  if [ $(echo "$CPU_USAGE >= $CPU_THRESHOLD" | bc) -eq 1 ]; then
    if [ $VALUE -eq 0 ]; then
      send_alert "CPU" "$CPU_USAGE" "$CPU_THRESHOLD"
    fi
  fi

  if [ $(echo "$MEMORY_USAGE >= $MEMORY_THRESHOLD" | bc) -eq 1 ]; then
    if [ $VALUE -eq 0 ]; then
      send_alert "RAM" "$MEMORY_USAGE" "$MEMORY_THRESHOLD"
    fi
  fi

  if [ $(echo "$DISK_USAGE >= $DISK_THRESHOLD" | bc) -eq 1 ]; then
    if [ $VALUE -eq 0 ]; then
      send_alert "DISK space" "$DISK_USAGE" "$DISK_THRESHOLD"
    fi
  fi

  VALUE=$((VALUE + 10))

  # Pause of 10 seconds to the next verification
  sleep 10
done
